// Generated by LispyScript v1.5.0
(function (___monad) {
  let mBind = ___monad.mBind,
    mResult = ___monad.mResult,
    mZero = ___monad.mZero,
    mPlus = ___monad.mPlus;
  let ____mResult = function (___arg) {
    return (((typeof(___arg) === "undefined") && (!(typeof(mZero) === "undefined"))) ?
      mZero :
      mResult(___arg));
  };
  return mBind((3 * 4),function (a) {
    return (function () {
      return ____mResult((function () {
        (a + b);
        (4 + 5);
        return a;
      })());
    })();
  });
})({
  mBind: function (mv,mf) {
    return mf(mv);
  },
  mResult: function (v) {
    return v;
  }
});
