// Generated by LispyScript v1.5.0
function pset_BANG(a_QUERY,b) {
  return [a_QUERY,"5578787"].join('');
}
(function() {
let yy_QUERY = dfd_STAR(33),
  poo = xxx_QUERY(((yy_QUERY ?
    2 :
    4) + 3));
(2 + 3);
return pset_BANG(yy_QUERY,"444");
})();
while (xyz < poo(34,6565)) {
(function() {
let yy_QUERY = dfd_STAR(33),
  poo = xxx_QUERY(((yy_QUERY ?
    2 :
    4) + 3));
(2 + 73);
return pset_BANG(yy_QUERY,"444");
})();
}
;
zzz.create([
  [
    a,
    (1 + 2),
    [
      b,
      3
    ],
    c
  ]
]);
(function() {
try {
  throw 10;;

} catch (err) {
return (function() {
return err;
})();
}
})();
