// Generated by LispyScript v1.5.0
let x = "asfsafaaaa\n     poo";
(function () {
  let recur = null,
    __xs = null,
    __f = function (a,times) {
      return ((times > a) ?
                (function() {
        (4 + 5);
        console.log(["a=",a].join(''));
        return recur((1 + a),times);
        })() :
        undefined);
    },
    __ret = __f;
  recur = function () {
    __xs = arguments;
    return ((!(typeof(__ret) === "undefined")) ?
            (function() {
      for (__ret=undefined; __ret===undefined; __ret=__f.apply(this,__xs));;
      return __ret;
      })() :
      undefined)
  };
  return recur(0,(3 * 5));
})();
(function () {
  let recur = null,
    __xs = null,
    __f = function (result,x) {
      return ((0 === x) ?
        result :
                (function() {
        result.push(x);
        return recur(result,(x - 1));
        })());
    },
    __ret = __f;
  recur = function () {
    __xs = arguments;
    return ((!(typeof(__ret) === "undefined")) ?
            (function() {
      for (__ret=undefined; __ret===undefined; __ret=__f.apply(this,__xs));;
      return __ret;
      })() :
      undefined)
  };
  return recur([],4);
})();
function pset_BANG(a_QUERY,b) {
  return [a_QUERY,"5578787"].join('');
}
(function() {
let yy_QUERY = dfd_STAR(33),
  poo = xxx_QUERY(((yy_QUERY ?
    2 :
    4) + 3));
(2 + 3);
return pset_BANG(yy_QUERY,"444");
})();
while (xyz < poo(34,6565)) {
(function() {
let yy_QUERY = dfd_STAR(33),
  poo = xxx_QUERY(((yy_QUERY ?
    2 :
    4) + 3));
(2 + 73);
return pset_BANG(yy_QUERY,"444");
})();
}
;
zzz.create([
  [
    a,
    (1 + 2),
    [
      b,
      3
    ],
    c
  ]
]);
(function() {
try {
  throw 10;;

} catch (err) {
return (function() {
return err;
})();
}
})();
