// Generated by LispyScript v1.5.0
(function () {
  let recur = null,
    __xs = null,
    __f = function (result,x) {
      return ((0 === x) ?
        result :
                (function() {
        result.push(x);
        return recur(result,(x - 1));
        })());
    },
    __ret = __f;
  recur = function () {
    __xs = arguments;
    return ((!(typeof(__ret) === "undefined")) ?
            (function() {
      for (__ret=undefined; __ret===undefined; __ret=__f.apply(this,__xs));;
      return __ret;
      })() :
      undefined)
  };
  return recur([],4);
})();
