// Generated by LispyScript v1.5.0
2;
let _STARxyz_poo_STAR = 3;
function xxxx() {
  return (1 * _STARxyz_poo_STAR);
}
var _STARVERSION_STAR = "1.0.0",
  _STARincludePaths_STAR = [],
  _STARnoSemiColon_QUERY_STAR = false,
  _STARindentSize_STAR = 3,
  _STARindent_STAR = -_STARindentSize_STAR;
