// Generated by LispyScript v1.5.0
(function (___m) {
  let ___u = function (v) {
    return (((typeof(v) === "undefined") && (!(typeof(___m.zero) === "undefined"))) ?
      ___m.zero :
      ___m.unit(v));
  };
  return ___m.bind([
    1,
    2,
    3
  ],function (a) {
    return ___m.bind([
      3,
      4,
      5
    ],function (b) {
      return (function () {
        return ___u((a + b));
      })();
    });
  });
})({
  bind: function (mv,mf) {
    return mv.map(mf).reduce(function (accum,val) {
      return accum.concat(val);
    },[]);
  },
  unit: function (v) {
    return [
      v
    ];
  },
  zero: [],
  plus: function () {
    return Array.prototype.slice.call(arguments).reduce(function (accum,val) {
      return accum.concat(val);
    },[]);
  }
});
