// Generated by LispyScript v1.5.0
require("./require");
var readline = require("readline"),
  ls = require("../lib/ls"),
  prefix = "lispy> ";
exports.runrepl = function () {
  let rl = readline.createInterface(process.stdin,process.stdout);
  rl.on('line',function (line) {
    (function() {
    try {
      let l = ls.transpile(line);
      return console.log(this.eval(l));

    } catch (err) {
    (function() {
    return console.log(err);
    })();
    }
    })();
    rl.setPrompt(prefix,prefix.length);
    return rl.prompt();
  });
  rl.on('close',function () {
    console.log("Bye!");
    return process.exit(0);
  });
  console.log([prefix,'LispyScript REPL v',ls.version].join(''));
  rl.setPrompt(prefix,prefix.length);
  return rl.prompt();
};
