// Generated by LispyScript v1.5.0
var fs = require("fs"),
  path = require("path"),
  ls = require("../lib/ls");
function xxx(module,filename) {
  let code = fs.readFileSync(filename,"utf8");
  return module._compile(ls.transpile(code,path.relative(process.cwd(),filename)),filename);
}
require.extensions[[
  ".kirby"
]] = xxx;
require.extensions[[
  ".lisp"
]] = xxx;
require("../src/macros");
