// Generated by LispyScript v1.5.0
var fs = require("fs"),
  path = require("path"),
  ls = require("../lib/ls");
  require.extensions[".ls"] = function(module,filename) {
  var code = fs.readFileSync(filename,"utf8");
  return module._compile(ls.transpile(code,path.relative(process.cwd(),filename)),filename);
};
  require("../src/macros");
